sephirah:
  server:
    grpc:
      addr: 0.0.0.0:9000
      timeout: 1s
  data:
    database:
      driver: sqlite3
      source: root:root@tcp(127.0.0.1:3306)/test
    redis:
      addr: 127.0.0.1:6379
      read_timeout: 0.2s
      write_timeout: 0.2s
  auth:
    salt: test
    issuer: test
    jwt_secret: test
mapper:
  data:
    cayley:
      store: memory
searcher:
  data:
    database:
      driver: mysql
      source: root:root@tcp(127.0.0.1:3306)/test
porter:
  data:
    database:
      driver: mysql
      source: root:root@tcp(127.0.0.1:3306)/test