sephirah:
  server:
    grpc:
      addr: 0.0.0.0:10000
      timeout: 1s
    grpc_web:
      addr: 0.0.0.0:10001
      timeout: 1s
  data:
    database:
      driver: sqlite3
  auth:
    salt: test
    issuer: test
    jwt_secret: test
  mq:
    driver: memory
mapper:
  data:
    cayley:
      store: memory
searcher:
  data:
porter:
  data:
    s3:
      end_point: 127.0.0.1:9000
      access_key: test
      secret_key: testtest
      use_ssl: false
    steam:
      api_key: