name: Test and coverage

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run coverage
        run: make init-test && make test-unit
#        run: make init-test && make test-all
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage-unit.out
#          files: ./coverage-unit.out,./coverage-goc.out
