name: release-please
on:
  push:
    branches:
      - master
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: librarian
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
  build:
    name: release ${{ matrix.goos }} ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.19.6.linux-amd64.tar.gz"
          project_path: "./cmd/librarian"
          binary_name: "librarian"
          extra_files: LICENSE README.md configs/config.yaml
          release_tag: ${{ needs.release-please.outputs.tag_name }}