name: release-please
on:
  push:
    branches:
      - master
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: go
          package-name: librarian
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
